import { Exercise } from '../types';

export const EXERCISES: Exercise[] = [
  {
    id: '1',
    name: 'Press banca',
    category: 'Pecho',
    equipment: 'Barra',
    difficulty: 'intermediate',
    pattern: 'Press horizontal',
    plane: 'Frontal',
    muscles: [
      { name: 'Pectoral mayor', percentage: 85 },
      { name: 'Tríceps', percentage: 60 },
      { name: 'Deltoides anterior', percentage: 45 },
    ],
    coachNotes: [
      'Retrae las escápulas antes de descolgar la barra.',
      'Pies planos en el suelo. Arco lumbar controlado.',
      'Bajada en 3 segundos. Explosivo arriba.',
      'Los codos a 45 grados, no en T.',
    ],
    videoDuration: '0:38',
  },
  {
    id: '2',
    name: 'Sentadilla profunda',
    category: 'Pierna',
    equipment: 'Barra',
    difficulty: 'advanced',
    pattern: 'Squat',
    plane: 'Sagital',
    muscles: [
      { name: 'Cuádriceps', percentage: 92 },
      { name: 'Glúteo mayor', percentage: 78 },
      { name: 'Isquiotibiales', percentage: 45 },
      { name: 'Core', percentage: 40 },
    ],
    coachNotes: [
      'Barra apoyada en trapecio bajo. Codos atrás.',
      'Pies anchura de hombros. Punteras ligeramente abiertas.',
      'Mete aire al diafragma y aprieta el core como si fueras a recibir un puñetazo.',
      'Baja con control. Rodillas en línea con los pies. Cadera atrás.',
      'Profundidad: cadera por debajo de la rodilla. Sin excusas.',
    ],
    videoDuration: '0:42',
  },
  {
    id: '3',
    name: 'Peso muerto',
    category: 'Espalda',
    equipment: 'Barra',
    difficulty: 'advanced',
    pattern: 'Hinge',
    plane: 'Sagital',
    muscles: [
      { name: 'Isquiotibiales', percentage: 88 },
      { name: 'Glúteo mayor', percentage: 85 },
      { name: 'Erectores espinales', percentage: 70 },
      { name: 'Trapecios', percentage: 55 },
    ],
    coachNotes: [
      'Barra sobre el mediopié. Pies a anchura de caderas.',
      'Agarre doble prono o mixto. Brazos perpendiculares.',
      'Empuja el suelo. No tires de la barra.',
      'Bloqueo completo arriba: glúteos apretados.',
    ],
    videoDuration: '0:35',
  },
  {
    id: '4',
    name: 'Dominadas estrictas',
    category: 'Espalda',
    equipment: 'Barra fija',
    difficulty: 'advanced',
    pattern: 'Pull vertical',
    plane: 'Frontal',
    muscles: [
      { name: 'Dorsal ancho', percentage: 90 },
      { name: 'Bíceps', percentage: 72 },
      { name: 'Romboides', percentage: 60 },
      { name: 'Core', percentage: 35 },
    ],
    coachNotes: [
      'Agarre prono, anchura de hombros o algo más.',
      'Parte desde colgado muerto. Sin trampolín.',
      'Pecho al frente, codos hacia las caderas.',
      'Bajada controlada. 3 segundos. Completa el ROM.',
    ],
    videoDuration: '0:28',
  },
  {
    id: '5',
    name: 'Press militar de pie',
    category: 'Hombro',
    equipment: 'Barra',
    difficulty: 'intermediate',
    pattern: 'Press vertical',
    plane: 'Frontal',
    muscles: [
      { name: 'Deltoides', percentage: 85 },
      { name: 'Tríceps', percentage: 65 },
      { name: 'Trapecios', percentage: 40 },
      { name: 'Core', percentage: 45 },
    ],
    coachNotes: [
      'Barra en clavículas. Pies a anchura de caderas.',
      'Core y glúteos apretados. No hiperextiendas la lumbar.',
      'Empuja la barra hacia arriba y ligeramente atrás.',
      'Bloqueo completo con bíceps junto a las orejas.',
    ],
    videoDuration: '0:32',
  },
  {
    id: '6',
    name: 'Front lever progresión',
    category: 'Calistenia',
    equipment: 'Barra fija',
    difficulty: 'elite',
    pattern: 'Core',
    plane: 'Sagital',
    muscles: [
      { name: 'Dorsal ancho', percentage: 95 },
      { name: 'Core', percentage: 90 },
      { name: 'Bíceps', percentage: 55 },
      { name: 'Romboides', percentage: 75 },
    ],
    coachNotes: [
      'Empieza con tucked front lever. Progresa lento.',
      'Hombros alejados de las orejas. Escápulas deprimidas.',
      'Cuerpo rígido como una tabla. Sin arco.',
      'Sosténlo 5–10 segundos. Descansa bien entre intentos.',
    ],
    videoDuration: '0:45',
  },
  {
    id: '7',
    name: 'Hip thrust con barra',
    category: 'Pierna',
    equipment: 'Barra',
    difficulty: 'intermediate',
    pattern: 'Hinge',
    plane: 'Sagital',
    muscles: [
      { name: 'Glúteo mayor', percentage: 95 },
      { name: 'Isquiotibiales', percentage: 60 },
      { name: 'Core', percentage: 30 },
    ],
    coachNotes: [
      'Espalda apoyada en banco. Barra sobre las caderas con pad.',
      'Pies planos, rodillas a 90° en la posición alta.',
      'Aprieta los glúteos al máximo arriba.',
      'Bajada controlada. No dejes que la barra rebote.',
    ],
    videoDuration: '0:30',
  },
  {
    id: '8',
    name: 'Muscle-up de anillas',
    category: 'Calistenia',
    equipment: 'Anillas',
    difficulty: 'elite',
    pattern: 'Push-Pull',
    plane: 'Sagital',
    muscles: [
      { name: 'Pectoral', percentage: 80 },
      { name: 'Dorsal', percentage: 85 },
      { name: 'Bíceps', percentage: 70 },
      { name: 'Tríceps', percentage: 75 },
      { name: 'Core', percentage: 60 },
    ],
    coachNotes: [
      'Necesitas dominada explosiva y fondos sólidos primero.',
      'La transición es lo más técnico: gira las muñecas.',
      'No uses el kip si eres principiante. Fuerza primero.',
      'Practica la transición por separado con cajón.',
    ],
    videoDuration: '0:50',
  },
  {
    id: '9',
    name: 'Aperturas en polea alta',
    category: 'Pecho',
    equipment: 'Polea',
    difficulty: 'intermediate',
    pattern: 'Fly',
    plane: 'Transversal',
    muscles: [
      { name: 'Pectoral mayor', percentage: 80 },
      { name: 'Deltoides anterior', percentage: 30 },
    ],
    coachNotes: [
      'Agarre neutro. Codos ligeramente flexionados durante todo el movimiento.',
      'Contrae el pecho al cruzar las manos en el centro.',
      'Controla la vuelta. No dejes que los cables tiren.',
    ],
    videoDuration: '0:25',
  },
  {
    id: '10',
    name: 'Fondos en paralelas',
    category: 'Pecho',
    equipment: 'Paralelas',
    difficulty: 'intermediate',
    pattern: 'Press',
    plane: 'Sagital',
    muscles: [
      { name: 'Pectoral', percentage: 75 },
      { name: 'Tríceps', percentage: 70 },
      { name: 'Deltoides anterior', percentage: 50 },
    ],
    coachNotes: [
      'Inclina el torso hacia adelante para enfatizar el pecho.',
      'Baja hasta que los hombros queden a la altura de los codos.',
      'Sube explosivo. Bloqueo completo.',
    ],
    videoDuration: '0:22',
  },
  {
    id: '11',
    name: 'Remo con barra',
    category: 'Espalda',
    equipment: 'Barra',
    difficulty: 'intermediate',
    pattern: 'Pull horizontal',
    plane: 'Sagital',
    muscles: [
      { name: 'Dorsal ancho', percentage: 80 },
      { name: 'Romboides', percentage: 70 },
      { name: 'Bíceps', percentage: 55 },
      { name: 'Trapecio medio', percentage: 60 },
    ],
    coachNotes: [
      'Torso a 45 grados. Espalda recta.',
      'Tira hacia el ombligo. Codos pegados al cuerpo.',
      'Aprieta la espalda en el punto de máxima contracción.',
    ],
    videoDuration: '0:30',
  },
  {
    id: '12',
    name: 'Press francés cuerda',
    category: 'Brazo',
    equipment: 'Polea',
    difficulty: 'intermediate',
    pattern: 'Press',
    plane: 'Sagital',
    muscles: [
      { name: 'Tríceps (cabeza larga)', percentage: 90 },
      { name: 'Tríceps (cabeza lateral)', percentage: 70 },
    ],
    coachNotes: [
      'Codos fijos. Solo se mueve el antebrazo.',
      'Extensión completa. Contrae el tríceps arriba.',
      'No permitas que los codos se abran.',
    ],
    videoDuration: '0:20',
  },
];
